name: C/C++ CI

on:
    push:
        branches: [ master ]
pull_request:
    branches: [ master ]

jobs:
<<<<<<< HEAD
  build:
      runs-on: windows-latest
      steps:
          - uses: actions/checkout@v2
          
          - name: Compile
            run: .\run-windows.bat
=======
    build:

        runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2

        - name: Compile
          run: bash run-linux.sh

    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v2
        - name: Compile
          run: bash run-mac.sh

    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
          # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
        - uses: seanmiddleditch/gha-setup-vsdevenv@master
>>>>>>> 191f321c3e2357acdaab716d15a758c2d4f24fad

        - name: Compile
          run: .\run-windows.bat

