name: C/C++ CI

# runs-on: macos-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      runs-on: windows-latest
      steps:
          - uses: actions/checkout@v2
          
          - name: Compile
            run: .\run-windows.bat


