name: C/C++ CI

# runs-on: macos-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-20.04
      steps:
          - uses: actions/checkout@v2
          - name: lib
            run: apt-get install -y libxrandr-dev
          - name: run
            run: bash run.sh

